# Generated by Django 2.0.2 on 2018-02-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Question Title')),
                ('related_statute', models.CharField(max_length=64, verbose_name='Related Statute')),
                ('rel_statute_link', models.CharField(max_length=64, verbose_name='Statute Link')),
                ('issue_summary', models.CharField(max_length=256, verbose_name='Summary')),
                ('issue_detail', models.CharField(max_length=1024, verbose_name='Detail')),
                ('issue_area', models.CharField(blank=True, choices=[('AUTO', 'AUTO'), ('GENERAL', 'GENERAL'), ('BAD FAITH', 'BAD FAITH'), ('CRIMINAL', 'CRIMINAL'), ('MEDICAL MALPRACTICE', 'MEDICAL MALPRACTICE'), ('NURSING HOME', 'NURSING HOME'), ('PREMISES', 'PREMISES'), ('PROPERTY INS', 'PROPERTY INS')], default='', max_length=255, null=True)),
                ('created_by', models.CharField(max_length=76)),
                ('related_document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=76)),
                ('county', models.CharField(max_length=76)),
                ('score', models.CharField(max_length=64)),
                ('marked_as_inapprop', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pleadings', 'Pleading'), ('discovery', 'Discovery'), ('motions', 'Motion'), ('orders', 'Order'), ('deposition', 'Deposition')], max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Case')),
            ],
        ),
    ]
