# Generated by Django 2.0.2 on 2018-02-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180226_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='created_by',
            field=models.CharField(default='samharden@gmail.com', max_length=76),
            preserve_default=False,
        ),
    ]
