# Generated by Django 2.0.2 on 2018-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_uploadfile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='related_document_desc',
            field=models.CharField(default='description', max_length=64, verbose_name='Description'),
        ),
    ]
