# Generated by Django 2.0.2 on 2018-02-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_case_related_document_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='related_cite',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='related_document_desc',
            field=models.CharField(max_length=64, verbose_name='Description'),
        ),
    ]
