# Generated by Django 2.0.2 on 2018-03-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20180228_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='doc_body',
            field=models.CharField(default='', max_length=60000),
        ),
    ]
