# Generated by Django 2.0.2 on 2018-03-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_uploadfile_doc_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='related_doc_body',
            field=models.CharField(default='', max_length=40000),
        ),
    ]
