# Generated by Django 2.0.2 on 2018-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_case_related_doc_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_type',
            field=models.CharField(choices=[('pleadings', 'Pleading'), ('discovery', 'Discovery'), ('motions', 'Motion'), ('orders', 'Order'), ('deposition', 'Deposition'), ('statute', 'Statute')], max_length=64),
        ),
    ]
