# Generated by Django 2.0.2 on 2018-03-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20180306_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='related_words',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
