# Generated by Django 2.0.2 on 2018-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_case_related_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='related_questions',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
