# Generated by Django 2.0.2 on 2018-03-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_case_related_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='related_questions',
        ),
        migrations.AddField(
            model_name='relatedquestions',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_number', to='questions.Case'),
        ),
        migrations.AddField(
            model_name='relatedquestions',
            name='related_questions',
            field=models.ManyToManyField(to='questions.Case'),
        ),
    ]
