# Generated by Django 2.0.2 on 2018-03-15 16:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20180309_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='issue_detail',
            field=tinymce.models.HTMLField(),
        ),
    ]
