# Generated by Django 2.0.4 on 2018-04-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20180315_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='rel_statute_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_number', to='knowledge_base.KB_Item'),
        ),
    ]
