# Generated by Django 2.0.4 on 2018-04-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20180406_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_type',
            field=models.CharField(choices=[('pleadings', 'Pleading'), ('discovery', 'Discovery'), ('motions', 'Motion'), ('orders', 'Order'), ('deposition', 'Deposition'), ('statute', 'Statute'), ('caselaw', 'Caselaw')], max_length=64),
        ),
    ]
