# Generated by Django 2.0.4 on 2018-05-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_case_related_cite_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='issue_area',
            field=models.CharField(blank=True, choices=[('AUTO', 'AUTO'), ('GENERAL', 'GENERAL'), ('BAD FAITH', 'BAD FAITH'), ('CRIMINAL', 'CRIMINAL'), ('MEDICAL MALPRACTICE', 'MEDICAL MALPRACTICE'), ('NURSING HOME', 'NURSING HOME'), ('PREMISES', 'PREMISES'), ('PROPERTY INS', 'PROPERTY INS'), ('CIVIL RIGHTS', 'CIVIL RIGHTS')], default='GENERAL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='related_doc_body',
            field=models.CharField(default='', max_length=60000),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='doc_body',
            field=models.CharField(default='', max_length=60000),
        ),
    ]
