# Generated by Django 2.0.4 on 2018-05-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20180515_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='issue_area',
            field=models.CharField(blank=True, choices=[('GENERAL', 'GENERAL'), ('COMPLAINT', 'COMPLAINT'), ('ANSWER', 'ANSWER'), ('AFFIRMATIVE DEFENSES', 'AFFIRMATIVE DEFENSES'), ('COURT PROCEDURE', 'COURT PROCEDURE'), ('JUDGE PREFERENCE', 'JUDGE PREFERENCE')], default='GENERAL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_type',
            field=models.CharField(choices=[('guide', 'Practice Guide'), ('statute', 'Statute')], max_length=64),
        ),
    ]
