# Generated by Django 2.0.4 on 2018-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20180518_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_type',
            field=models.CharField(choices=[('guide', 'Practice Guide'), ('statute', 'Statute'), ('element', 'Element')], max_length=64),
        ),
    ]
