# Generated by Django 2.0.4 on 2018-05-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20180519_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_type',
            field=models.CharField(choices=[('guide', 'Practice Guide'), ('statute', 'Statute'), ('element', 'Element'), ('grounds', 'Grounds')], max_length=64),
        ),
    ]
