# Generated by Django 2.0.4 on 2018-05-22 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20180522_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='issue_area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.Practicearea'),
            preserve_default=False,
        ),
    ]
