# Generated by Django 2.0.4 on 2018-08-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20180822_2209'),
        ('questions', '0024_auto_20180822_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='visible_to',
            field=models.ManyToManyField(blank=True, default='', to='common.LegalAidOrg'),
        ),
    ]
