# Generated by Django 2.0.2 on 2018-02-23 21:22

from django.db import migrations, models
# import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('chapter', models.CharField(max_length=64, verbose_name='Title')),
                ('heading', models.CharField(max_length=64, verbose_name='Heading')),
                ('statute_number', models.CharField(max_length=64, verbose_name='Related Statute')),
                ('statute_body', models.CharField(max_length=40000, verbose_name='Body')),
            ],
        ),
    ]
