# Generated by Django 2.0.2 on 2018-02-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statute',
            name='statute_body',
            field=models.CharField(max_length=60000, verbose_name='Body'),
        ),
    ]
