# Generated by Django 2.0.2 on 2018-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_auto_20180302_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kb_item',
            old_name='statute_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='kb_item',
            old_name='chapter',
            new_name='statute_chapter',
        ),
        migrations.RenameField(
            model_name='kb_item',
            old_name='heading',
            new_name='statute_heading',
        ),
        migrations.AddField(
            model_name='kb_item',
            name='kb_area',
            field=models.CharField(choices=[('AUTO', 'AUTO'), ('GENERAL', 'GENERAL'), ('BAD FAITH', 'BAD FAITH'), ('CRIMINAL', 'CRIMINAL'), ('MEDICAL MALPRACTICE', 'MEDICAL MALPRACTICE'), ('NURSING HOME', 'NURSING HOME'), ('PREMISES', 'PREMISES'), ('PROPERTY INS', 'PROPERTY INS')], default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='kb_type',
            field=models.CharField(choices=[('pleadings', 'Pleading'), ('discovery', 'Discovery'), ('motions', 'Motion'), ('orders', 'Order'), ('deposition', 'Deposition'), ('statute', 'Statute')], max_length=64),
        ),
    ]
