# Generated by Django 2.0.4 on 2018-04-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0006_kb_item_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='kb_item',
            name='citation',
            field=models.CharField(default='', max_length=64, verbose_name='Citation'),
        ),
        migrations.AddField(
            model_name='kb_item',
            name='judge',
            field=models.CharField(default='', max_length=64, verbose_name='Judge'),
        ),
    ]
