# Generated by Django 2.0.4 on 2018-05-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0008_auto_20180416_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='body',
            field=models.CharField(max_length=60000, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='document',
            name='practice_area',
            field=models.CharField(choices=[('AUTO', 'AUTO'), ('GENERAL', 'GENERAL'), ('BAD FAITH', 'BAD FAITH'), ('CRIMINAL', 'CRIMINAL'), ('MEDICAL MALPRACTICE', 'MEDICAL MALPRACTICE'), ('NURSING HOME', 'NURSING HOME'), ('PREMISES', 'PREMISES'), ('PROPERTY INS', 'PROPERTY INS'), ('CIVIL RIGHTS', 'CIVIL RIGHTS')], max_length=64),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='body',
            field=models.CharField(max_length=60000, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='kb_area',
            field=models.CharField(choices=[('AUTO', 'AUTO'), ('GENERAL', 'GENERAL'), ('BAD FAITH', 'BAD FAITH'), ('CRIMINAL', 'CRIMINAL'), ('MEDICAL MALPRACTICE', 'MEDICAL MALPRACTICE'), ('NURSING HOME', 'NURSING HOME'), ('PREMISES', 'PREMISES'), ('PROPERTY INS', 'PROPERTY INS'), ('CIVIL RIGHTS', 'CIVIL RIGHTS')], max_length=64),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='statute_chapter',
            field=models.CharField(max_length=64, verbose_name='Statute Chapter'),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='statute_number',
            field=models.CharField(max_length=64, verbose_name='Statute Number'),
        ),
    ]
