# Generated by Django 2.0.4 on 2018-05-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0009_auto_20180515_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='kb_item',
            name='plain_body',
            field=models.TextField(default='', max_length=60000, verbose_name='Plain Body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kb_item',
            name='trigger',
            field=models.CharField(default='', max_length=600, verbose_name='Plain Body'),
        ),
        migrations.AlterField(
            model_name='document',
            name='practice_area',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('COMPLAINT', 'COMPLAINT'), ('ANSWER', 'ANSWER'), ('AFFIRMATIVE DEFENSES', 'AFFIRMATIVE DEFENSES'), ('COURT PROCEDURE', 'COURT PROCEDURE'), ('JUDGE PREFERENCE', 'JUDGE PREFERENCE')], max_length=64),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='body',
            field=models.TextField(default='', max_length=60000, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='citation',
            field=models.CharField(default='', max_length=64, verbose_name='Case Citation'),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='kb_area',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('COMPLAINT', 'COMPLAINT'), ('ANSWER', 'ANSWER'), ('AFFIRMATIVE DEFENSES', 'AFFIRMATIVE DEFENSES'), ('COURT PROCEDURE', 'COURT PROCEDURE'), ('JUDGE PREFERENCE', 'JUDGE PREFERENCE')], max_length=64, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='kb_type',
            field=models.CharField(choices=[('guide', 'Practice Guide'), ('statute', 'Statute')], max_length=64, verbose_name='Type of Item'),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='state',
            field=models.CharField(choices=[('AL', 'AL'), ('CA', 'CA'), ('FL', 'FL'), ('GA', 'GA'), ('IL', 'IL'), ('MS', 'MS'), ('NY', 'NY'), ('NC', 'NC'), ('SC', 'SC'), ('TN', 'TN'), ('TX', 'TX')], default='FL', max_length=64),
        ),
    ]
