# Generated by Django 2.0.4 on 2018-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0010_auto_20180518_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='kb_item',
            name='aff_resp',
            field=models.CharField(default='', max_length=600, verbose_name='If Affirmate Response to Trigge'),
        ),
        migrations.AddField(
            model_name='kb_item',
            name='neg_resp',
            field=models.CharField(default='', max_length=600, verbose_name='If Negative Response to Trigger'),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='body',
            field=models.TextField(default='', max_length=60000, verbose_name='HTML Body'),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='kb_type',
            field=models.CharField(choices=[('guide', 'Practice Guide'), ('statute', 'Statute'), ('element', 'Element')], max_length=64, verbose_name='Type of Item'),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='state',
            field=models.CharField(choices=[('AL', 'AL'), ('CA', 'CA'), ('FL', 'FL'), ('GA', 'GA'), ('KY', 'KY'), ('IL', 'IL'), ('MS', 'MS'), ('NY', 'NY'), ('NC', 'NC'), ('SC', 'SC'), ('TN', 'TN'), ('TX', 'TX')], default='FL', max_length=64),
        ),
        migrations.AlterField(
            model_name='kb_item',
            name='trigger',
            field=models.CharField(default='', max_length=600, verbose_name='Trigger'),
        ),
    ]
