# Generated by Django 2.0.4 on 2018-05-21 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0012_auto_20180522_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kb_item',
            name='kb_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Casetype'),
        ),
    ]
