# Generated by Django 2.0.4 on 2018-05-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0013_auto_20180522_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kb_item',
            name='kb_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Practicearea'),
        ),
    ]
