# Generated by Django 2.0.4 on 2018-06-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0015_auto_20180522_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kb_item',
            options={'ordering': ['kb_area']},
        ),
        migrations.RemoveField(
            model_name='kb_item',
            name='kb_type',
        ),
    ]
