# Generated by Django 2.0.4 on 2018-06-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0016_auto_20180614_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='kb_item',
            name='related_document',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
