# Generated by Django 2.0.2 on 2018-02-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
