# Generated by Django 2.0.2 on 2018-02-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_comment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
