# Generated by Django 2.0.2 on 2018-03-05 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20180226_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_2_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('score', models.CharField(default=0, max_length=64)),
                ('commented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orig_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='common.Comment')),
            ],
        ),
    ]
