# Generated by Django 2.0.4 on 2018-05-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_comment_2_comment_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_practice_area',
            field=models.CharField(choices=[('AUTO', 'AUTO'), ('GENERAL', 'GENERAL'), ('BAD FAITH', 'BAD FAITH'), ('CRIMINAL', 'CRIMINAL'), ('MEDICAL MALPRACTICE', 'MEDICAL MALPRACTICE'), ('NURSING HOME', 'NURSING HOME'), ('PREMISES', 'PREMISES'), ('PROPERTY INS', 'PROPERTY INS'), ('CIVIL RIGHTS', 'CIVIL RIGHTS')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_practice_area',
            field=models.CharField(choices=[('AUTO', 'AUTO'), ('GENERAL', 'GENERAL'), ('BAD FAITH', 'BAD FAITH'), ('CRIMINAL', 'CRIMINAL'), ('MEDICAL MALPRACTICE', 'MEDICAL MALPRACTICE'), ('NURSING HOME', 'NURSING HOME'), ('PREMISES', 'PREMISES'), ('PROPERTY INS', 'PROPERTY INS'), ('CIVIL RIGHTS', 'CIVIL RIGHTS')], default='NA', max_length=64),
        ),
    ]
