# Generated by Django 2.0.4 on 2018-05-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20180515_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_practice_area',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('COMPLAINT', 'COMPLAINT'), ('ANSWER', 'ANSWER'), ('AFFIRMATIVE DEFENSES', 'AFFIRMATIVE DEFENSES'), ('COURT PROCEDURE', 'COURT PROCEDURE'), ('JUDGE PREFERENCE', 'JUDGE PREFERENCE')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondary_practice_area',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('COMPLAINT', 'COMPLAINT'), ('ANSWER', 'ANSWER'), ('AFFIRMATIVE DEFENSES', 'AFFIRMATIVE DEFENSES'), ('COURT PROCEDURE', 'COURT PROCEDURE'), ('JUDGE PREFERENCE', 'JUDGE PREFERENCE')], default='NA', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('AL', 'AL'), ('CA', 'CA'), ('FL', 'FL'), ('GA', 'GA'), ('IL', 'IL'), ('MS', 'MS'), ('NY', 'NY'), ('NC', 'NC'), ('SC', 'SC'), ('TN', 'TN'), ('TX', 'TX')], max_length=64),
        ),
    ]
