# Generated by Django 2.0.4 on 2018-06-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20180608_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='primary_practice_area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_practice_area',
        ),
    ]
