# Generated by Django 2.0.4 on 2018-08-22 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20180614_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAidOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('street_address', models.CharField(max_length=1000, verbose_name='Address')),
                ('city', models.CharField(max_length=500, verbose_name='City')),
                ('state', models.CharField(max_length=400, verbose_name='State')),
                ('zip_code', models.CharField(max_length=400, verbose_name='Zip')),
                ('website_url', models.CharField(max_length=1000, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='legal_aid_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.LegalAidOrg'),
        ),
    ]
