# Generated by Django 2.0.4 on 2018-08-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20180822_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalaidorg',
            name='website_url',
            field=models.CharField(max_length=1000, verbose_name='Website'),
        ),
    ]
